package com.finance.finance_tracker.util;

import com.finance.finance_tracker.dto.MonthlyReportResponse;
import com.finance.finance_tracker.enums.Category;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Map;

@Component
public class PdfGenerator {

    public ByteArrayInputStream generateMonthlyReport(MonthlyReportResponse report) {

        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

            Paragraph title = new Paragraph("PERSONAL FINANCE TRACKER", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph subTitle = new Paragraph("Monthly Expense Report", headingFont);
            subTitle.setAlignment(Element.ALIGN_CENTER);
            document.add(subTitle);

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Month : " + report.getMonth(), normalFont));
            document.add(new Paragraph("Year : " + report.getYear(), normalFont));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Total Income : ₹ " + report.getTotalIncome(), normalFont));
            document.add(new Paragraph("Total Expense : ₹ " + report.getTotalExpense(), normalFont));
            document.add(new Paragraph("Savings : ₹ " + report.getSavings(), normalFont));
            document.add(new Paragraph("Total Transactions : " + report.getTotalTransactions(), normalFont));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Category-wise Expenses", headingFont));
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);

            table.addCell("Category");
            table.addCell("Amount");

            for (Map.Entry<Category, java.math.BigDecimal> entry : report.getCategoryWiseExpense().entrySet()) {

                table.addCell(entry.getKey().name());
                table.addCell("₹ " + entry.getValue());

            }

            document.add(table);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by Personal Finance Tracker", headingFont));

            document.close();

        } catch (Exception e) {
            throw new RuntimeException("Error while generating PDF", e);
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}